# Generated by Django 4.1.3 on 2022-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Fulfilled", "Fulfilled"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("On Transit", "On Transit"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
