# Generated by Django 4.1.2 on 2022-10-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="door_number",
            new_name="room_number",
        ),
    ]
