# Generated by Django 4.1.3 on 2022-11-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_door_number_location_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('F', 'Completed'), ('C', 'Cancelled'), ('T', 'On Transit'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
