# Generated by Django 4.1.3 on 2022-11-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
        ('cart', '0005_cartitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.rider')),
            ],
        ),
    ]
