# Generated by Django 4.1.3 on 2022-11-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_status"),
        ("rider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrider",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.location",
            ),
        ),
    ]
