# Generated by Django 4.1.3 on 2022-11-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0003_rider_dob_rider_name_rider_national_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rider",
            old_name="name",
            new_name="brand",
        ),
    ]
