# Generated by Django 4.1.3 on 2022-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0004_rename_name_rider_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="dob",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
