# Generated by Django 4.0.6 on 2022-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',), 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='creation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='checked_out',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('P', 'Processing'), ('C', 'Cancelled'), ('D', 'Delivered')], db_index=True, default='R', max_length=1),
        ),
    ]
