# Generated by Django 4.0.6 on 2022-09-27 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 27, 3, 56, 42, 35202, tzinfo=utc), verbose_name='order date'),
        ),
    ]
