# Generated by Django 4.0.6 on 2022-08-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('T', 'On Transit'), ('D', 'Delivered'), ('C', 'Cancelled')], db_index=True, default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('O', 'In Progress'), ('C', 'Cancelled'), ('F', 'Fulfilled')], db_index=True, default='R', max_length=1),
        ),
        migrations.DeleteModel(
            name='ClientOrder',
        ),
    ]
