# Generated by Django 4.0.6 on 2022-08-24 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 8, 24, 22, 8, 49, 766670, tzinfo=utc), verbose_name='creation date'),
        ),
    ]
