# Generated by Django 4.0.6 on 2022-09-21 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 9, 21, 18, 33, 8, 129868, tzinfo=utc), verbose_name='creation date'),
        ),
    ]
