# Generated by Django 4.1.3 on 2022-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mpesaReceiptNumber", models.CharField(max_length=20)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("transactionDate", models.DateTimeField()),
                ("phone", models.CharField(max_length=13)),
            ],
            options={
                "verbose_name": "Mpesa Payment",
                "verbose_name_plural": "Mpesa Payments",
            },
        ),
    ]
