# Generated by Django 4.0.6 on 2022-09-30 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='category//%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litre'), ('ml', 'Millilitre'), ('in', 'Inches')], default='kg', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='unit price')),
                ('image', models.ImageField(upload_to='product//%Y/%m/%d/')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('label',),
            },
        ),
    ]
