# Generated by Django 4.1.3 on 2022-12-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.ImageField(upload_to="category//%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "categories",
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilograms"),
                            ("g", "Grams"),
                            ("l", "Litre"),
                            ("ml", "Millilitre"),
                            ("in", "Inches"),
                        ],
                        default="kg",
                        help_text="Quantity measurement metrics",
                        max_length=2,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="unit price"
                    ),
                ),
                ("image", models.ImageField(upload_to="product//%Y/%m/%d/")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("stock", models.PositiveIntegerField(default=1, verbose_name="stock")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("label",),
            },
        ),
    ]
