# Generated by Django 4.0.6 on 2022-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litre'), ('ml', 'Millilitre'), ('in', 'Inches')], default='kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='category//%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product//%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
